### ISSUE TITLE
Bug: Hot Reload/Restart throws error on writes

### ISSUE THREAD

**Issue by joshpetit** [iamcco/coc-flutter#132]
Thanks a lot for this extension, it's been a real help so having this issue solved would save me!
**Describe the bug**
Whenever you write to a file, this error is thrown:
```
[coc.nvim]: TypeError: i.find is not a function
    at /home/joshu/.config/coc/extensions/node_modules/coc-flutter/out/index.js:44:2571
    at CallbackList.invoke (/home/joshu/.local/share/nvim/plugged/coc.nvim/build/index.js:12523:35)
    at Emitter27.fire (/home/joshu/.local/share/nvim/plugged/coc.nvim/build/index.js:12574:34)
    at Workspace.onBufWritePost (/home/joshu/.local/share/nvim/plugged/coc.nvim/build/index.js:34430:33)
    at /home/joshu/.local/share/nvim/plugged/coc.nvim/build/index.js:18374:39
    at new Promise (<anonymous>)
    at wrappedhandler (/home/joshu/.local/share/nvim/plugged/coc.nvim/build/index.js:18371:42)
    at /home/joshu/.local/share/nvim/plugged/coc.nvim/build/index.js:18351:47
    at Array.map (<anonymous>)
    at Events.fire (/home/joshu/.local/share/nvim/plugged/coc.nvim/build/index.js:18351:35)

```

**To Reproduce**
1. Run flutter application
2. Write to a file

**Expected behavior**
The application to reload

**Desktop (please complete the following information):**
 - OS: Arch
 - Vim or Neovim: NeoVim
 - (Neo)vim version: 0.5.0

**Output channel:**

1. Set `"flutter.trace.server":   "verbose"`
2. Restart coc using `:CocRestart`
3. Reproduce the issue
4. `:CocCommand workspace.showOutput` open output list and select `flutter`

Paste Log from above:

```

[Trace - 8:40:30 AM] Received request 'window/workDoneProgress/create - (9)'.
Params: {
    "token": "ANALYZING"
}


[Trace - 8:40:30 AM] Sending response 'window/workDoneProgress/create - (9)'. Processing request took 0ms
No result returned.


[Trace - 8:40:31 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///home/joshu/projects/APP_DIRECTORY/lib/story.dart",
    "diagnostics": []
}


[Trace - 8:40:31 AM] Received notification 'dart/textDocument/publishClosingLabels'.
Params: {
    "uri": "file:///home/joshu/projects/APP_DIRECTORY/lib/story.dart",
    "labels": [
        {
            "range": {
                "start": {
                    "line": 24,
                    "character": 40
                },
                "end": {
                    "line": 134,
                    "character": 7
                }
            },
            "label": "Storybook"
        },
        {
            "range": {
                "start": {
                    "line": 26,
                    "character": 18
                },
                "end": {
                    "line": 133,
                    "character": 9
                }
            },
            "label": "<Story>[]"
        },
        {
            "range": {
                "start": {
                    "line": 27,
                    "character": 10
                },
                "end": {
                    "line": 40,
                    "character": 11
                }
            },
            "label": "Story"
        },
        {
            "range": {
                "start": {
                    "line": 30,
                    "character": 44
                },
                "end": {
                    "line": 39,
                    "character": 13
                }
            },
            "label": "StringItem"
        },
        {
            "range": {
                "start": {
                    "line": 41,
                    "character": 10
                },
                "end": {
                    "line": 50,
                    "character": 11
                }
            },
            "label": "Story"
        },
        {
            "range": {
                "start": {
                    "line": 44,
                    "character": 44
                },
                "end": {
                    "line": 49,
                    "character": 13
                }
            },
            "label": "BoolItem"
        },
        {
            "range": {
                "start": {
                    "line": 51,
                    "character": 10
                },
                "end": {
                    "line": 62,
                    "character": 11
                }
            },
            "label": "Story"
        },
        {
            "range": {
                "start": {
                    "line": 54,
                    "character": 44
                },
                "end": {
                    "line": 61,
                    "character": 13
                }
            },
            "label": "SingleChildScrollView"
        },
        {
            "range": {
                "start": {
                    "line": 55,
                    "character": 21
                },
                "end": {
                    "line": 60,
                    "character": 15
                }
            },
            "label": "SignupFormCast"
        },
        {
            "range": {
                "start": {
                    "line": 63,
                    "character": 10
                },
                "end": {
                    "line": 72,
                    "character": 11
                }
            },
            "label": "Story"
        },
        {
            "range": {
                "start": {
                    "line": 66,
                    "character": 44
                },
                "end": {
                    "line": 71,
                    "character": 13
                }
            },
            "label": "SigninFormCast"
        },
        {
            "range": {
                "start": {
                    "line": 73,
                    "character": 10
                },
                "end": {
                    "line": 80,
                    "character": 11
                }
            },
            "label": "Story"
        },
        {
            "range": {
                "start": {
                    "line": 76,
                    "character": 44
                },
                "end": {
                    "line": 79,
                    "character": 13
                }
            },
            "label": "SplashScreenCast"
        },
        {
            "range": {
                "start": {
                    "line": 81,
                    "character": 10
                },
                "end": {
                    "line": 87,
                    "character": 11
                }
            },
            "label": "Story"
        },
        {
            "range": {
                "start": {
                    "line": 84,
                    "character": 44
                },
                "end": {
                    "line": 86,
                    "character": 13
                }
            },
            "label": "AddEventFormCast"
        },
        {
            "range": {
                "start": {
                    "line": 88,
                    "character": 10
                },
                "end": {
                    "line": 101,
                    "character": 11
                }
            },
            "label": "Story"
        },
        {
            "range": {
                "start": {
                    "line": 91,
                    "character": 44
                },
                "end": {
                    "line": 100,
                    "character": 13
                }
            },
            "label": "EventsScreenCast"
        },
        {
            "range": {
                "start": {
                    "line": 92,
                    "character": 29
                },
                "end": {
                    "line": 97,
                    "character": 71
                }
            },
            "label": "List.generate"
        },
        {
            "range": {
                "start": {
                    "line": 102,
                    "character": 10
                },
                "end": {
                    "line": 123,
                    "character": 11
                }
            },
            "label": "Story"
        },
        {
            "range": {
                "start": {
                    "line": 105,
                    "character": 44
                },
                "end": {
                    "line": 122,
                    "character": 13
                }
            },
            "label": "MaterialApp"
        },
        {
            "range": {
                "start": {
                    "line": 107,
                    "character": 20
                },
                "end": {
                    "line": 121,
                    "character": 15
                }
            },
            "label": "Scaffold"
        },
        {
            "range": {
                "start": {
                    "line": 108,
                    "character": 37
                },
                "end": {
                    "line": 120,
                    "character": 17
                }
            },
            "label": "Ms5NavigationBar"
        },
        {
            "range": {
                "start": {
                    "line": 113,
                    "character": 29
                },
                "end": {
                    "line": 118,
                    "character": 21
                }
            },
            "label": "<Option<int>>[]"
        },
        {
            "range": {
                "start": {
                    "line": 124,
                    "character": 10
                },
                "end": {
                    "line": 132,
                    "character": 11
                }
            },
            "label": "Story.simple"
        },
        {
            "range": {
                "start": {
                    "line": 126,
                    "character": 19
                },
                "end": {
                    "line": 131,
                    "character": 13
                }
            },
            "label": "TextField"
        },
        {
            "range": {
                "start": {
                    "line": 127,
                    "character": 26
                },
                "end": {
                    "line": 130,
                    "character": 15
                }
            },
            "label": "InputDecoration"
        }
    ]
}


[Trace - 8:40:31 AM] Received notification '$/progress'.
Params: {
    "token": "ANALYZING",
    "value": {
        "kind": "begin",
        "title": "Analyzing…"
    }
}


[Trace - 8:40:31 AM] Received notification '$/progress'.
Params: {
    "token": "ANALYZING",
    "value": {
        "kind": "end"
    }
}
```

**Comment by Kavantix** [comment]
Strange that hot reload is not working
Can you share the `flutter.dev` output
And share which versions you are using of coc-flutter coc.nvim and node

**Comment by iamcco** [comment]
I catch the issue.

the latest version of coc.nvim change the type of `diagnosticManager.getDiagnostics`

code impelement: https://github.com/neoclide/coc.nvim/blob/master/src/diagnostic/manager.ts#L213

No match typibg: https://github.com/neoclide/coc.nvim/blob/master/typings/index.d.ts#L7649


So the code will breaking with latest coc.nvim

https://github.com/iamcco/coc-flutter/blob/master/src/provider/hotreload.ts#L16

**Comment by iamcco** [comment]
Please test with https://github.com/iamcco/coc-flutter/pull/133
