### ISSUE TITLE
Error on flutter.run

### ISSUE THREAD

**Issue by dvogt23** [iamcco/coc-flutter#33]
Is this a known error? Could anyone help?

```
vim version: NVIM v0.5.0-5a5c2f0
node version: v13.11.0
coc.nvim version: 0.0.77-9d846734a2
term: xterm-256color
platform: darwin

## Messages
[coc.nvim] Source "flutter" recreated
[coc.nvim] error: UnhandledRejection: request error nvim_win_set_option - Option 'foldcolumn' requires a string value
Error: request error nvim_win_set_option - Option 'foldcolumn' requires a string value
    at .vim/bundle/coc.nvim/build/index.js:14243:32
    at NvimTransport.parseMessage (.vim/bundle/coc.nvim/build/index.js:10847:17)
    at DecodeStream.<anonymous> (.vim/bundle/coc.nvim/build/index.js:10817:18)
    at DecodeStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at DecodeStream.Readable.push (_stream_readable.js:214:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (.vim/bundle/coc.nvim/build/index.js:13767:12)
    at DecodeBuffer.flush (.vim/bundle/coc.nvim/build/index.js:12757:12)
[coc.nvim] error: UnhandledRejection: request error nvim_win_set_option - Option 'foldcolumn' requires a string value
Error: request error nvim_win_set_option - Option 'foldcolumn' requires a string value
    at .vim/bundle/coc.nvim/build/index.js:14243:32
    at NvimTransport.parseMessage (.vim/bundle/coc.nvim/build/index.js:10847:17)
    at DecodeStream.<anonymous> (.vim/bundle/coc.nvim/build/index.js:10817:18)
    at DecodeStream.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at DecodeStream.Readable.push (_stream_readable.js:214:10)
    at DecodeStream.Transform.push (_stream_transform.js:152:32)
    at DecodeBuffer.DecodeStream.decoder.push (.vim/bundle/coc.nvim/build/index.js:13767:12)
    at DecodeBuffer.flush (.vim/bundle/coc.nvim/build/index.js:12757:12)
```

**Comment by lepiku** [comment]
Now it's broken on my machine.
```
Platform: arch linux
Nvim Version: NVIM v0.4.3
Node version: v10.18.0
term: urxvt

[coc.nvim] error: UnhandledRejection: request error nvim_win_set_option - Option 'foldcolumn' requires an int
eger value
Error: request error nvim_win_set_option - Option 'foldcolumn' requires an integer value
    at transport.request (/home/dimas/.local/share/nvim/plugged/coc.nvim/build/index.js:14243:32)
    at NvimTransport.parseMessage (/home/dimas/.local/share/nvim/plugged/coc.nvim/build/index.js:10847:17)
    at DecodeStream.NvimTransport.decodeStream.on (/home/dimas/.local/share/nvim/plugged/coc.nvim/build/index
.js:10817:18)
    at DecodeStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at DecodeStream.Readable.push (_stream_readable.js:223:10)
    at DecodeStream.Transform.push (_stream_transform.js:151:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/dimas/.local/share/nvim/plugged/coc.nvim/build/index.js:
13767:12)
    at DecodeBuffer.flush (/home/dimas/.local/share/nvim/plugged/coc.nvim/build/index.js:12757:12)
UnhandledRejection: request error nvim_win_set_option - Option 'foldcolumn' requires an integer value
Error: request error nvim_win_set_option - Option 'foldcolumn' requires an integer value
    at transport.request (/home/dimas/.local/share/nvim/plugged/coc.nvim/build/index.js:14243:32)
    at NvimTransport.parseMessage (/home/dimas/.local/share/nvim/plugged/coc.nvim/build/index.js:10847:17)
    at DecodeStream.NvimTransport.decodeStream.on (/home/dimas/.local/share/nvim/plugged/coc.nvim/build/index
.js:10817:18)
    at DecodeStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at DecodeStream.Readable.push (_stream_readable.js:223:10)
    at DecodeStream.Transform.push (_stream_transform.js:151:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/dimas/.local/share/nvim/plugged/coc.nvim/build/index.js:
13767:12)
    at DecodeBuffer.flush (/home/dimas/.local/share/nvim/plugged/coc.nvim/build/index.js:12757:12)
```

**Comment by iamcco** [comment]
OK, It seems that neovim latest version change to string and stable version still init
