### ISSUE TITLE
An error is output when :CocCommand flutter.run is executed on Vim8

### ISSUE THREAD

**Issue by yaegassy** [iamcco/coc-flutter#6]
When `:CocCommand flutter.run` is executed in `Vim8`, an error is output.

```
[coc.nvim] error:     at VimTransport.request (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6355:13)
```

`flutter run` seems to be running, but I was worried about the error being output.

There is no problem with Neovim.

**Comment by iamcco** [comment]
Using `mess` to see the whole error message.

**Comment by yaegassy** [comment]
Hi, `:messages` output.

I'm sorry,  `xxxx` masks the username for privacy reasons.

```
[coc.nvim] error: method: nvim_create_buf not supported.
[coc.nvim] error: method: nvim_open_win not supported.
[coc.nvim] error: UnhandledRejection: Converting circular structure to JSON
[coc.nvim] error: TypeError: Converting circular structure to JSON
[coc.nvim] error:     at JSON.stringify (<anonymous>)
[coc.nvim] error:     at toString (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6225:21)
[coc.nvim] error:     at more. .arr.map.o (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6237:39)
[coc.nvim] error:     at Array.map (<anonymous>)
[coc.nvim] error:     at Logger.getText (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6237:30)
[coc.nvim] error:     at Logger.error (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6254:27)
[coc.nvim] error:     at Connection.send (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6457:20)
[coc.nvim] error:     at Connection.call (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6474:14)
[coc.nvim] error:     at Request.request (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6509:25)
[coc.nvim] error:     at VimTransport.request (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6355:13)
[coc.nvim] error: method: nvim_create_buf not supported.
[coc.nvim] error: method: nvim_open_win not supported.
[coc.nvim] error: UnhandledRejection: Converting circular structure to JSON
[coc.nvim] error: TypeError: Converting circular structure to JSON
[coc.nvim] error:     at JSON.stringify (<anonymous>)
[coc.nvim] error:     at toString (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6225:21)
[coc.nvim] error:     at more. .arr.map.o (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6237:39)
[coc.nvim] error:     at Array.map (<anonymous>)
[coc.nvim] error:     at Logger.getText (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6237:30)
[coc.nvim] error:     at Logger.error (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6254:27)
[coc.nvim] error:     at Connection.send (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6457:20)
[coc.nvim] error:     at Connection.call (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6474:14)
[coc.nvim] error:     at Request.request (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6509:25)
[coc.nvim] error:     at VimTransport.request (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6355:13)
[coc.nvim] error: method: nvim_create_buf not supported.
[coc.nvim] error: method: nvim_open_win not supported.
[coc.nvim] error: UnhandledRejection: Converting circular structure to JSON
[coc.nvim] error: TypeError: Converting circular structure to JSON
[coc.nvim] error:     at JSON.stringify (<anonymous>)
[coc.nvim] error:     at toString (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6225:21)
[coc.nvim] error:     at more. .arr.map.o (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6237:39)
[coc.nvim] error:     at Array.map (<anonymous>)
[coc.nvim] error:     at Logger.getText (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6237:30)
[coc.nvim] error:     at Logger.error (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6254:27)
[coc.nvim] error:     at Connection.send (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6457:20)
[coc.nvim] error:     at Connection.call (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6474:14)
[coc.nvim] error:     at Request.request (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6509:25)
[coc.nvim] error:     at VimTransport.request (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6355:13)
[coc.nvim] error: method: nvim_create_buf not supported.
[coc.nvim] error: method: nvim_open_win not supported.
[coc.nvim] error: UnhandledRejection: Converting circular structure to JSON
[coc.nvim] error: TypeError: Converting circular structure to JSON
[coc.nvim] error:     at JSON.stringify (<anonymous>)
[coc.nvim] error:     at toString (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6225:21)
[coc.nvim] error:     at more. .arr.map.o (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6237:39)
[coc.nvim] error:     at Array.map (<anonymous>)
[coc.nvim] error:     at Logger.getText (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6237:30)
[coc.nvim] error:     at Logger.error (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6254:27)
[coc.nvim] error:     at Connection.send (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6457:20)
[coc.nvim] error:     at Connection.call (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6474:14)
[coc.nvim] error:     at Request.request (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6509:25)
[coc.nvim] error:     at VimTransport.request (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6355:13)
[coc.nvim] error: method: nvim_create_buf not supported.
[coc.nvim] error: method: nvim_open_win not supported.
[coc.nvim] error: UnhandledRejection: Converting circular structure to JSON
[coc.nvim] error: TypeError: Converting circular structure to JSON
[coc.nvim] error:     at JSON.stringify (<anonymous>)
[coc.nvim] error:     at toString (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6225:21)
[coc.nvim] error:     at more. .arr.map.o (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6237:39)
[coc.nvim] error:     at Array.map (<anonymous>)
[coc.nvim] error:     at Logger.getText (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6237:30)
[coc.nvim] error:     at Logger.error (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6254:27)
[coc.nvim] error:     at Connection.send (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6457:20)
[coc.nvim] error:     at Connection.call (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6474:14)
[coc.nvim] error:     at Request.request (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6509:25)
[coc.nvim] error:     at VimTransport.request (/Users/xxxx/.vim/plugged/coc.nvim/build/index.js:6355:13)
```

**Comment by iamcco** [comment]
OK，I know what happen, will fix it soon.
