### ISSUE TITLE
Flutter attach not working

### ISSUE THREAD

**Issue by Nohac** [iamcco/coc-flutter#71]
**Describe the bug**
I used to be able to run this command `flutter.attach --debug-uri http://127.0.0.1:50300 -d flutter-tester` in order to attach to the observatory started by `hover` when using `go-flutter-desktop`. This is no longer the case.

**Expected behavior**
I should be able to attach to the observatory running on `http://127.0.0.1:50300` and be able to perform hot reloading as I used to.

## CocInfo

```
vim version: NVIM v0.5.0-823-g42ffa2d62
node version: v15.3.0
coc.nvim version: 0.0.79
coc.nvim directory: /home/user/.config/nvim/plug.vim/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2020-11-28T12:38:03.711 INFO (pid:14040) [extensions] - Skipped load vim plugin from "/home/user/.config/nvim/plug.vim/coc-tsserver", "coc-tsserver" already global extension.
2020-11-28T12:38:03.712 INFO (pid:14040) [extensions] - Skipped load vim plugin from "/home/user/.config/nvim/plug.vim/coc-marketplace", "coc-marketplace" already global extension.
2020-11-28T12:38:03.740 INFO (pid:14040) [services] - registered service "languageserver.clangd"
2020-11-28T12:38:03.740 INFO (pid:14040) [services] - registered service "languageserver.godot"
2020-11-28T12:38:03.759 INFO (pid:14040) [services] - registered service "diagnostic-languageserver"
2020-11-28T12:38:03.767 INFO (pid:14040) [services] - registered service "eslint"
2020-11-28T12:38:03.880 INFO (pid:14040) [plugin] - coc.nvim 0.0.79 initialized with node: v15.3.0 after 193ms
2020-11-28T12:38:05.466 INFO (pid:14040) [services] - registered service "flutter"
2020-11-28T12:38:05.466 INFO (pid:14040) [services] - flutter analysis server state change: stopped => starting
2020-11-28T12:38:05.471 INFO (pid:14040) [language-client-index] - Language server "flutter" started with 14103
2020-11-28T12:38:05.739 INFO (pid:14040) [services] - flutter analysis server state change: starting => running
2020-11-28T12:38:05.741 INFO (pid:14040) [services] - service flutter started
2020-11-28T12:38:17.146 INFO (pid:14040) [completion-complete] - Results from: around
2020-11-28T12:38:17.541 INFO (pid:14040) [willSaveHandler] - Will save cost: 134
2020-11-28T12:38:37.470 INFO (pid:14040) [completion-complete] - Results from: around
2020-11-28T12:38:37.837 INFO (pid:14040) [willSaveHandler] - Will save cost: 64
2020-11-28T12:38:47.183 ERROR (pid:14040) [node-client] - request error on "nvim_win_set_option" [ 'foldcolumn', 1 ] Option 'foldcolumn' requires a string value Error
    at Window.request (/home/user/.config/nvim/plug.vim/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:29:21)
    at Window.setOption (/home/user/.config/nvim/plug.vim/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:80:21)
    at o.<anonymous> (/home/user/.config/coc/extensions/node_modules/coc-flutter/out/index.js:33:40426)
    at Generator.next (<anonymous>)
    at o (/home/user/.config/coc/extensions/node_modules/coc-flutter/out/index.js:33:39473)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
2020-11-28T12:38:47.738 ERROR (pid:14040) [node-client] - request error on "nvim_win_set_option" [ 'foldcolumn', 1 ] Option 'foldcolumn' requires a string value Error
    at Window.request (/home/user/.config/nvim/plug.vim/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:29:21)
    at Window.setOption (/home/user/.config/nvim/plug.vim/coc.nvim/node_modules/@chemzqm/neovim/lib/api/Base.js:80:21)
    at o.<anonymous> (/home/user/.config/coc/extensions/node_modules/coc-flutter/out/index.js:33:40426)
    at Generator.next (<anonymous>)
    at o (/home/user/.config/coc/extensions/node_modules/coc-flutter/out/index.js:33:39473)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
2020-11-28T12:38:49.344 INFO (pid:14040) [completion-complete] - Results from: around
2020-11-28T12:38:49.706 INFO (pid:14040) [willSaveHandler] - Will save cost: 68
```

Worth noting that `request error on "nvim_win_set_option" ...` appears after I run the `flutter.attach` command.

**Output channel:**

1. Set `"flutter.trace.server":   "verbose"`
2. Reproduce the issue
3. `:CocList output` open output list and select `flutter`

Log:
```
[coc.nvim] List output not found
```

**Comment by iamcco** [comment]
What's your coc-flutter version?

**Comment by Kavantix** [comment]
@Nohac are you still running into this?

**Comment by Nohac** [comment]
No, I've been using normal flutter for desktop so it's been working out of the box, sorry for keeping this issue open for so long.
