### ISSUE TITLE
Getting error and warning when launching emulator and can't update mobile.

### ISSUE THREAD

**Issue by TornaxO7** [iamcco/coc-flutter#75]
**Describe the bug**
First bug: If I start the emulator, than I'm getting the following error:
```vim
2020-12-20T00:31:17.591 ERROR (pid:1157264) [node-client] - resumeNotification not called within same tick: Error
    at NeovimClient.pauseNotification (/home/tornax/.vim/plugged/coc.nvim/build/index.js:11914:21)
    at o.<anonymous> (/home/tornax/.config/coc/extensions/node_modules/coc-flutter/out/index.js:33:40150)
    at Generator.next (<anonymous>)
    at o (/home/tornax/.config/coc/extensions/node_modules/coc-flutter/out/index.js:33:39473)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
2020-12-20T00:31:17.631 ERROR (pid:1157264) [node-client] - resumeNotification not called within same tick: Error
    at NeovimClient.pauseNotification (/home/tornax/.vim/plugged/coc.nvim/build/index.js:11914:21)
    at StatusLine.setStatusText (/home/tornax/.vim/plugged/coc.nvim/build/index.js:45839:18)
    at Timeout._onTimeout (/home/tornax/.vim/plugged/coc.nvim/build/index.js:45785:18)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
2020-12-20T00:31:19.506 WARN (pid:1157264) [events] - Handler of InputChar blocked more than 2s: Error
    at Events.on (/home/tornax/.vim/plugged/coc.nvim/build/index.js:16529:25)
    at ListManager.init (/home/tornax/.vim/plugged/coc.nvim/build/index.js:83892:26)
    at Plugin.init (/home/tornax/.vim/plugged/coc.nvim/build/index.js:23935:31)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /home/tornax/.vim/plugged/coc.nvim/build/index.js:11579:13
2020-12-20T00:31:30.047 INFO (pid:1157264) [attach] - receive notification: showInfo []
```
Here's a live demo:
![GIF](https://user-images.githubusercontent.com/50843046/102701777-d3a18580-425a-11eb-9428-bd1a515eefb7.gif)

**How to reproduce**:
1. Open a `main.dart`
2. Open an emulator
3. Open `:CocInfo`

Anyway this "bug" isn't that important. The second bug is more important:

Hot-reload doesn't work. Here's a demo:
![GIF2](https://user-images.githubusercontent.com/50843046/102702811-47498f80-4267-11eb-82f8-52510724a2b0.gif)

So that's the error message:
```
2020-12-20T01:59:25.335 ERROR (pid:40894) [node-client] - resumeNotification not called within same tick: Error
    at NeovimClient.pauseNotification (/home/tornax/.vim/plugged/coc.nvim/build/index.js:11914:21)
    at o.<anonymous> (/home/tornax/.config/coc/extensions/node_modules/coc-flutter/out/index.js:33:40150)
    at Generator.next (<anonymous>)
    at o (/home/tornax/.config/coc/extensions/node_modules/coc-flutter/out/index.js:33:39473)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

How to reproduce it:
1. Open a `.dart` file
2. Start an emulator with `:CocCommand flutter.emulators`
3. attach it with `:CocCommand flutter.attach`
4. Execute the `flutter.dev.hotReload` command

**Expected behavior**
I expected to be able to load the project into the emulator. I'd be so happy if this could work because Android Studio is somehow buggy currently (the widgets from Android Studio are behaving weird) and VSCode doesn't really work either and your gif was looking so smooth!

**Desktop (please complete the following information):**
 - OS: Arch Linux, Kernel: 5.9.14-arch1-1
 - Vim or Neovim: Neovim
 - (Neo)vim version:
 ```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Output channel:**

1. Set `"flutter.trace.server":   "verbose"`
2. Reproduce the issue
3. `:CocList output` open output list and select `flutter`
I can't execute `:CocList output`. This pops up:
```
[coc.nvim] List output not found
```

**Comment by TornaxO7** [comment]
Nvm, I just need to do `:CocCommand flutter.run` instead of `flutter.attach`. I misunderstood these commands. It's working now. Thank you so much for this plugin!!!!!!
